spring.application.name=produk
server.port = 8081

spring.datasource.url=jdbc:h2:mem:produk;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123456
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
<<<<<<< HEAD
spring.jpa.hibernate.dd1-auto=update
eureka.client.service-url.default=http://localhost:8761/eureka/
=======
spring.jpa.hibernate.dd1-auto=update
>>>>>>> a16e237a440170cc0995d29df8e379368b33135d
